name: CodeTour watch

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    codetour-watch:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v3

            - name: 'Watch CodeTour changes'
              uses: pozil/codetour-watch@v1.5.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
